// The lockfile sync, tested the way every gate script here is: the decision is
// a pure function over text, so these need no filesystem and no mocking
// library. What they pin is the SILENT direction — a sync that quietly does
// nothing leaves a release branch that cannot publish, and reads identically
// to one that had nothing to do.

import { describe, it } from "node:test";
import assert from "node:assert/strict";

import { syncCargoLockVersion } from "./sync-cargo-lock.mjs";

const LOCK =
  "# This file is automatically @generated by Cargo.\n" +
  "version = 4\n\n" +
  '[[package]]\nname = "itoa"\nversion = "1.0.18"\n' +
  'source = "registry+https://github.com/rust-lang/crates.io-index"\n\n' +
  '[[package]]\nname = "lattice-rule-sdk"\nversion = "0.9.0"\n' +
  'dependencies = [\n "serde",\n]\n';

describe("syncCargoLockVersion", () => {
  it("writes the manifest's version into the named package's entry", () => {
    const { text, changed } = syncCargoLockVersion(LOCK, "lattice-rule-sdk", "0.10.0");
    assert.equal(changed, true);
    assert.match(text, /name = "lattice-rule-sdk"\nversion = "0\.10\.0"/u);
  });

  it("leaves every other package's version alone", () => {
    // The lock is a flat array of same-shaped entries, so a rewrite that
    // matched on the version line alone would bump a dependency's pin and
    // produce a lock cargo rejects for a reason nothing in the diff explains.
    const { text } = syncCargoLockVersion(LOCK, "lattice-rule-sdk", "0.10.0");
    assert.match(text, /name = "itoa"\nversion = "1\.0\.18"/u);
  });

  it("preserves the rest of the file byte for byte", () => {
    const { text } = syncCargoLockVersion(LOCK, "lattice-rule-sdk", "0.10.0");
    assert.equal(text, LOCK.replace('version = "0.9.0"', 'version = "0.10.0"'));
  });

  it("reports no change when the lock already records the version", () => {
    const { text, changed } = syncCargoLockVersion(LOCK, "lattice-rule-sdk", "0.9.0");
    assert.equal(changed, false);
    assert.equal(text, LOCK);
  });

  it("throws rather than reporting 'nothing to do' when the package is absent", () => {
    // The silent direction this whole file exists for: returning
    // `changed: false` here is byte-identical to the in-step case above, so a
    // renamed crate would leave the release branch unbumped under a green
    // sync step, and the failure would surface in the publish job instead —
    // after the tag is cut and can no longer be moved.
    assert.throws(
      () => syncCargoLockVersion(LOCK, "renamed-crate", "0.10.0"),
      /carries no \[\[package\]\] entry named "renamed-crate"/u,
    );
  });
});
